services:
  examiner_db:
    container_name: examiner_db
    image: postgres:16.3-alpine3.20
    restart: always
    env_file:  
      - .env.production
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - examiner_network 

  django:
    container_name: examiner_main
    build: .
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --workers 4 --bind 0.0.0.0:8000 mysurvey.wsgi:application"
    env_file:  
      - .env.production
    depends_on:
      - examiner_db
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    networks:
      - examiner_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "5052:8080"
    networks:
      - examiner_network

  nginx:
    build: ./nginx
    container_name: examiner_nginx
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "7777:80"
    depends_on:
      - django
    networks:
      - examiner_network


volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  examiner_network:
    name: examiner_network
    driver: bridge
