
services:
  survey_db:
    restart: always
    image: postgres:16.3-alpine3.20
    container_name: survey_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root@123"
      POSTGRES_DB: "survey"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/docker/volumes/survey_postgres_data/_data:/var/lib/postgresql/data/

  django:
    restart: always
    build: .
    container_name: survey_main
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --workers 4 --bind 0.0.0.0:8000 mysurvey.wsgi:application"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    environment:
      DJANGO_SETTINGS_MODULE: mysurvey.production
    depends_on:
      - survey_db

  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:8080"

  nginx:
    build: ./nginx
    container_name: survey_nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "7777:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume: