# Generated by Django 5.1.4 on 2024-12-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('radio', 'Один вариант ответа'), ('checkbox', 'Множественный выбор'), ('select', 'Выпадающий список'), ('combo', 'Комбинированный (Да/Нет + Текст)')], max_length=50),
        ),
        migrations.CreateModel(
            name='DependentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_answers', to='survey.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_answers', to='survey.response')),
            ],
        ),
    ]
