# Generated by Django 5.1.4 on 2024-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_question_question_type_dependentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='requires_comment',
            field=models.BooleanField(default=False),
        ),
    ]
