# Generated by Django 5.1.4 on 2025-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_exam_question_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='employee_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
