# Generated by Django 5.1.4 on 2025-05-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_response_employee_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='employee_name',
        ),
    ]
