# Generated by Django 5.1.4 on 2024-12-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('textarea', 'Расширенный ответ'), ('radio', 'Один вариант ответа'), ('select', 'Выпадающий список'), ('combo', 'Комбинированный (Да/Нет + Текст)')], max_length=50),
        ),
    ]
