# Generated by Django 5.1.4 on 2024-12-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_question_is_unique_alter_question_question_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DependentAnswer',
        ),
    ]
