# Generated by Django 5.1.4 on 2024-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_delete_dependentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('textarea', 'Расширенный ответ'), ('radio', 'Один вариант ответа'), ('checkbox', 'Множественный выбор'), ('select', 'Выпадающий список'), ('combo', 'Комбинированный (Да/Нет + Текст)')], max_length=50),
        ),
    ]
